n1=input('digite algo ')
print('O tipo primitivo desse valor é ',type(n1))
print('{} é um número?'.format(n1), end=' ')
print(n1.isnumeric())
print('{} é alfabético?'.format(n1), end=' ')
print(n1.isalpha())
print('{} é alfanumérico?'.format(n1), end=' ')
print(n1.isalnum())
print('{} é um número decimal?'.format(n1), end=' ')
print(n1.isdecimal())
print('{} é composta somente por dígitos?'.format(n1), end=' ')
print(n1.isdigit())
print('{} é um identificador válido?'.format(n1), end=' ')
print(n1.isidentifier())
print('{} está toda em letras maiúsculas?'.format(n1), end=' ')
print(n1.isupper())
print('{} está toda em letras minúsculas?'.format(n1), end=' ')
print(n1.islower())
print('{} está capitalizada?'.format(n1), end=' ')
print(n1.istitle())
print("{} é um caractere 'printável'?".format(n1), end=' ')
print(n1.isprintable())
print('{} é composta somente por espaços?'.format(n1), end=' ')
print(n1.isspace())
print('{} é composta somente por caracteres ascii?'.format(n1), end=' ')
print(n1.isascii())
print('{} é aplicável ao recurso __init_subclass__?'.format(n1), end=' ')
print(n1.__init_subclass__())
