nome=str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome ...')
print('Seu nome em maiúsculas é {}.'.format(nome.upper()))
print('Seu nome em minúsculas é {}.'.format(nome.lower()))
#print('Seu nome ao todo tem {} letras.'.format(len(nome)-nome.count(' ')))
#print('Seu nome ao todo tem {} letras.'.format(len(nome.replace(' ',''))))
print('Seu nome ao todo tem {} letras.'.format(len(''.join(nome.split()))))
splitnome=nome.split()
#print('Seu primeiro nome é {} e ele tem {} letras.'.format(splitnome[0],len(splitnome[0])))
print('Seu primeiro nome é {} e ele tem {} letras.'.format(splitnome[0],nome.find(' ')))
